// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHYdUH16A8BSTpirmtGWwCyAVZon2WL9M',
    appId: '1:1052609869278:web:2f5c71e543b0d1849e194f',
    messagingSenderId: '1052609869278',
    projectId: 'buonappetito-c14e7',
    authDomain: 'buonappetito-c14e7.firebaseapp.com',
    storageBucket: 'buonappetito-c14e7.appspot.com',
    measurementId: 'G-0MJ3H2M45Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYbt-x3JSfi1rDKggrgLbgZG8cUGaVK04',
    appId: '1:1052609869278:android:2b787fa6a6e095eb9e194f',
    messagingSenderId: '1052609869278',
    projectId: 'buonappetito-c14e7',
    storageBucket: 'buonappetito-c14e7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwKkdmTEEJRL4tyPwgPeMM3bXjE7dQX10',
    appId: '1:1052609869278:ios:707b338d8a58cfaa9e194f',
    messagingSenderId: '1052609869278',
    projectId: 'buonappetito-c14e7',
    storageBucket: 'buonappetito-c14e7.appspot.com',
    iosBundleId: 'com.fpdedomi.buonappetito',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwKkdmTEEJRL4tyPwgPeMM3bXjE7dQX10',
    appId: '1:1052609869278:ios:b0a71067879916a39e194f',
    messagingSenderId: '1052609869278',
    projectId: 'buonappetito-c14e7',
    storageBucket: 'buonappetito-c14e7.appspot.com',
    iosBundleId: 'com.example.buonappetito',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHYdUH16A8BSTpirmtGWwCyAVZon2WL9M',
    appId: '1:1052609869278:web:682cfd04d6d538dd9e194f',
    messagingSenderId: '1052609869278',
    projectId: 'buonappetito-c14e7',
    authDomain: 'buonappetito-c14e7.firebaseapp.com',
    storageBucket: 'buonappetito-c14e7.appspot.com',
    measurementId: 'G-9DBBVS66MD',
  );

}